// AUTO-GENERATED by scripts/apply-env-config.mjs at build time.
// Do not edit by hand — set values as environment variables in Vercel.
// Committed default (all blank) runs the site in demo mode.

export const ENV = {
  "FIREBASE_API_KEY": "",
  "FIREBASE_AUTH_DOMAIN": "",
  "FIREBASE_PROJECT_ID": "",
  "FIREBASE_APP_ID": "",
  "APPCHECK_SITE_KEY": "",
  "MAP_PROVIDER": "carto",
  "MAPPLS_KEY": "",
  "REPORT_EMAIL": "vikas070696@gmail.com"
};
