// ============================================================================
// Tiny HTTP helpers shared by the three write endpoints.
//
// Responses are always JSON of the shape { error, message } on failure, so
// js/store.js can turn a code into a human sentence without parsing prose.
// ============================================================================

/** An error carrying the HTTP status and machine-readable code to return. */
export class ApiError extends Error {
  constructor(status, code, message, extra) {
    super(message || code);
    this.status = status;
    this.code = code;
    this.extra = extra || null;
  }
}

export const fail = (status, code, message, extra) => new ApiError(status, code, message, extra);

export function send(res, status, body) {
  res.status(status);
  res.setHeader('content-type', 'application/json; charset=utf-8');
  // Never let a CDN or browser cache a mutation's answer.
  res.setHeader('cache-control', 'no-store');
  res.end(JSON.stringify(body));
}

/**
 * Vercel parses JSON bodies for us, but only when the content-type says so —
 * parse defensively rather than trusting the caller to set the header.
 */
export function readBody(req) {
  const b = req.body;
  if (b && typeof b === 'object' && !Buffer.isBuffer(b)) return b;
  const raw = Buffer.isBuffer(b) ? b.toString('utf8') : typeof b === 'string' ? b : '';
  if (!raw) return {};
  try { return JSON.parse(raw); } catch { throw fail(400, 'bad_request', 'Body must be JSON.'); }
}

/**
 * Same-origin gate. Browsers always attach `Origin` to a cross-origin POST
 * (and to same-origin fetch POSTs too), so comparing it to the host we were
 * reached on cheaply rejects other sites driving this API with a visitor's
 * connection. It is not the real defence — Turnstile is — but it costs
 * nothing and it keeps the endpoints from being a free write proxy.
 */
export function assertSameOrigin(req) {
  const origin = req.headers.origin;
  const host = req.headers['x-forwarded-host'] || req.headers.host;
  if (!origin || !host) throw fail(403, 'forbidden', 'Missing origin.');
  let originHost;
  try { originHost = new URL(origin).host; } catch { throw fail(403, 'forbidden', 'Bad origin.'); }
  if (originHost !== host) throw fail(403, 'forbidden', 'Cross-origin requests are not allowed.');
}

/**
 * Recognise the ways the Firestore/credential layer fails and turn them into
 * a diagnosis in the function log. These all used to be an anonymous 500 —
 * indistinguishable from a code bug, when the actual fix is re-pasting an env
 * var. The gRPC status number rides on err.code; credential-material problems
 * surface as auth-library messages instead, so match those by text.
 */
function explainInfraError(err) {
  const msg = String(err?.message || '');
  if (/DECODER routines|Failed to parse private key|PEM/i.test(msg)) {
    return [
      'bad_service_account',
      'The service-account private_key is mangled — almost always newlines eaten by a dashboard ' +
      'paste. Re-paste FIREBASE_SERVICE_ACCOUNT as BASE64 (api/_lib/firestore.js accepts either): ' +
      'node -e "console.log(require(\'fs\').readFileSync(\'serviceAccount.json\').toString(\'base64\'))"',
    ];
  }
  if (/service account object|must contain a string/i.test(msg)) {
    return [
      'bad_service_account',
      'FIREBASE_SERVICE_ACCOUNT is JSON but not a service-account KEY — this is usually the ' +
      'Firebase web config pasted by mistake. The right file comes from Project settings → ' +
      'Service accounts → Generate new private key, and contains "private_key" and "client_email".',
    ];
  }
  if (/invalid_grant|invalid_rapt|account not found/i.test(msg)) {
    return [
      'bad_service_account',
      'Firestore rejected the service-account credential — the key was revoked/deleted, or the ' +
      'system clock disagrees with Google. Generate a fresh key and re-paste FIREBASE_SERVICE_ACCOUNT.',
    ];
  }
  switch (err?.code) {
    case 5:  return ['database_not_found',
      'Firestore says NOT_FOUND for the database itself — FIREBASE_SERVICE_ACCOUNT probably belongs ' +
      'to a DIFFERENT project than the events database. Check its project_id field.'];
    case 7:  return ['firestore_permission_denied',
      'The service account is not allowed to use Firestore. Use the key generated by Firebase ' +
      'console → Project settings → Service accounts → Generate new private key.'];
    case 16: return ['bad_service_account',
      'UNAUTHENTICATED from Firestore — the credential is not valid. Re-generate and re-paste ' +
      'FIREBASE_SERVICE_ACCOUNT.'];
    case 4: case 14: return ['firestore_unavailable',
      'Firestore timed out / unavailable — transient, retrying usually works.'];
    default: return null;
  }
}

/**
 * Wraps a handler so every endpoint gets: POST-only, same-origin, JSON body,
 * and uniform error mapping. Unexpected throws become a 500 with no internals
 * leaked to the client (they go to the function log instead).
 */
export function handler(fn) {
  return async (req, res) => {
    try {
      if (req.method === 'OPTIONS') { res.status(204).end(); return; }
      if (req.method !== 'POST') throw fail(405, 'method_not_allowed', 'Use POST.');
      assertSameOrigin(req);
      const out = await fn(req, readBody(req));
      send(res, 200, { ok: true, ...(out || {}) });
    } catch (err) {
      if (err instanceof ApiError) {
        send(res, err.status, { ok: false, error: err.code, message: err.message, ...(err.extra || {}) });
        return;
      }
      const known = explainInfraError(err);
      if (known) {
        // Full diagnosis to the log; a stable code but no internals to the
        // client (which half of the server config is broken is not a thing
        // to broadcast).
        console.error(`[api] ${known[0]}: ${known[1]}\n  underlying:`, err?.message || err);
        send(res, 503, { ok: false, error: known[0], message: 'The server could not reach its database.' });
        return;
      }
      console.error('[api] unhandled error:', err);
      send(res, 500, { ok: false, error: 'server_error', message: 'Something went wrong.' });
    }
  };
}
